SELECT USER
FROM DUAL;
--==>> SCOTT

--○ 테이블 생성(TBL_MEMBERLIST)
CREATE TABLE TBL_MEMBERLIST
( ID    VARCHAR2(30)
, PW    VARCHAR2(20) NOT NULL
, NAME  VARCHAR2(50) NOT NULL
, TEL   VARCHAR2(50) NOT NULL
, EMAIL VARCHAR2(100)
, CONSTRAINT MEMBERLIST_ID_PK PRIMARY KEY(ID)
, CONSTRAINT MEMBERLIST_TEL_UK UNIQUE(TEL)
);
--==>> Table TBL_MEMBERLIST이(가) 생성되었습니다.

DESC TBL_MEMBERLIST;

-- 인원수 
SELECT COUNT(*) AS COUNT FROM TBL_MEMBERLIST
;

-- 데이터 입력
INSERT INTO TBL_MEMBERLIST(ID, PW, NAME, TEL, EMAIL) VALUES('아이디', '비밀번호', '이름', '전화번호', '이메일')
;

-- 데이터 출력
SELECT ID, PW, NAME, TEL, EMAIL FROM TBL_MEMBERLIST
;

-- 커밋
COMMIT;
--==>> 커밋 완료.